[package]
name = "trunk"
version = "0.9.0"
edition = "2018"
description = "Build, bundle & ship your Rust WASM application to the web."
license = "MIT/Apache-2.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
repository = "https://github.com/thedodd/trunk"
readme = "README.md"
categories = ["command-line-utilities", "wasm", "web-programming"]
keywords = ["wasm", "bundler", "web", "build-tool", "compiler"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1"
async-process = "1"
cargo_metadata = "0.12"
console = "0.14"
dunce = "1"
envy = "0.4"
fs_extra = "1"
futures = "0.3"
http-types = "2"
indicatif = "0.15"
lazy_static = "1.4.0"
nipper = { git = "https://github.com/thedodd/nipper.git", branch = "iter-attrs" }
notify = "4"
open = "1"
remove_dir_all = "0.6"
sass-rs = "0.2.2"
seahash = "4"
serde = { version="1", features=["derive"] }
structopt = "0.3"
structopt-derive = "0.4"
tokio = { version="1", features=[
    # See https://docs.rs/tokio/1.2.0/tokio/#feature-flags
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "process",
    "macros",
    "sync",
    "fs"
]}
tokio-tungstenite = "0.13.0"
toml = "0.5"
warp = "0.3.0"

[dev-dependencies]
insta = "0.16.1"
